/**
 * Opções fiscais compartilhadas (NF-e) — extraídas de
 * `Admin/Products/FiscalForm.vue` (2026-08-09) pra também servir a emissão
 * manual de nota fiscal (`Admin/Invoices/Emitir.vue`), que precisa dos
 * mesmos códigos pra item digitado na hora (produto fora do catálogo ou
 * serviço avulso). Única fonte — mudar aqui atualiza os dois formulários.
 */

export const ORIGEM_OPTIONS = [
    { value: 0, label: '0 — Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8' },
    { value: 1, label: '1 — Estrangeira: Importação direta, exceto a indicada no código 6' },
    { value: 2, label: '2 — Estrangeira: Adquirida no mercado interno, exceto a indicada no código 7' },
    { value: 3, label: '3 — Nacional, com Conteúdo de Importação superior a 40% e inferior ou igual a 70%' },
    { value: 4, label: '4 — Nacional, produção conforme processos produtivos básicos' },
    { value: 5, label: '5 — Nacional, com Conteúdo de Importação inferior ou igual a 40%' },
    { value: 6, label: '6 — Estrangeira: Importação direta, sem similar nacional, lista CAMEX e gás natural' },
    { value: 7, label: '7 — Estrangeira: Adquirida no mercado interno, sem similar nacional, lista CAMEX e gás natural' },
    { value: 8, label: '8 — Nacional, com Conteúdo de Importação superior a 70%' },
];

export const CSOSN_OPTIONS = [
    { value: '101', label: '101 — Tributada pelo Simples Nacional com permissão de crédito' },
    { value: '102', label: '102 — Tributada pelo Simples Nacional sem permissão de crédito' },
    { value: '103', label: '103 — Isenção do ICMS no Simples Nacional para faixa de receita bruta' },
    { value: '201', label: '201 — Tributada pelo Simples Nacional com crédito e cobrança do ICMS por ST' },
    { value: '202', label: '202 — Tributada pelo Simples Nacional sem crédito e cobrança do ICMS por ST' },
    { value: '203', label: '203 — Isenção do ICMS no Simples Nacional para faixa de receita bruta e cobrança por ST' },
    { value: '300', label: '300 — Imune' },
    { value: '400', label: '400 — Não tributada pelo Simples Nacional' },
    { value: '500', label: '500 — ICMS cobrado anteriormente por substituição tributária ou por antecipação' },
    { value: '900', label: '900 — Outros' },
];

export const PIS_COFINS_CST_OPTIONS = [
    { value: '01', label: '01 — Operação Tributável com Alíquota Básica' },
    { value: '02', label: '02 — Operação Tributável com Alíquota Diferenciada' },
    { value: '03', label: '03 — Operação Tributável com Alíquota por Unidade de Medida de Produto' },
    { value: '04', label: '04 — Operação Tributável Monofásica – Revenda a Alíquota Zero' },
    { value: '05', label: '05 — Operação Tributável por Substituição Tributária' },
    { value: '06', label: '06 — Operação Tributável a Alíquota Zero' },
    { value: '07', label: '07 — Operação Isenta da Contribuição' },
    { value: '08', label: '08 — Operação sem Incidência da Contribuição' },
    { value: '09', label: '09 — Operação com Suspensão da Contribuição' },
    { value: '49', label: '49 — Outras Operações de Saída' },
    { value: '50', label: '50 — Direito a Crédito – Vinculado Exclusivamente a Receita Tributada no Mercado Interno' },
    { value: '51', label: '51 — Direito a Crédito – Vinculado Exclusivamente a Receita Não Tributada no Mercado Interno' },
    { value: '52', label: '52 — Direito a Crédito – Vinculado Exclusivamente a Receita de Exportação' },
    { value: '53', label: '53 — Direito a Crédito – Vinculado a Receitas Tributadas e Não-Tributadas no Mercado Interno' },
    { value: '54', label: '54 — Direito a Crédito – Vinculado a Receitas Tributadas no Mercado Interno e de Exportação' },
    { value: '55', label: '55 — Direito a Crédito – Vinculado a Receitas Não-Tributadas no Mercado Interno e de Exportação' },
    { value: '56', label: '56 — Direito a Crédito – Vinculado a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação' },
    { value: '60', label: '60 — Crédito Presumido – Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno' },
    { value: '61', label: '61 — Crédito Presumido – Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno' },
    { value: '62', label: '62 — Crédito Presumido – Aquisição Vinculada Exclusivamente a Receita de Exportação' },
    { value: '63', label: '63 — Crédito Presumido – Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno' },
    { value: '64', label: '64 — Crédito Presumido – Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação' },
    { value: '65', label: '65 — Crédito Presumido – Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação' },
    { value: '66', label: '66 — Crédito Presumido – Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação' },
    { value: '67', label: '67 — Crédito Presumido – Outras Operações' },
    { value: '70', label: '70 — Operação de Aquisição sem Direito a Crédito' },
    { value: '71', label: '71 — Operação de Aquisição com Isenção' },
    { value: '72', label: '72 — Operação de Aquisição com Suspensão' },
    { value: '73', label: '73 — Operação de Aquisição a Alíquota Zero' },
    { value: '74', label: '74 — Operação de Aquisição sem Incidência da Contribuição' },
    { value: '75', label: '75 — Operação de Aquisição por Substituição Tributária' },
    { value: '98', label: '98 — Outras Operações de Entrada' },
    { value: '99', label: '99 — Outras Operações' },
];

export const UNIDADE_MEDIDA_OPTIONS = [
    { value: 'AMP', label: 'AMPOLA' },
    { value: 'BALDE', label: 'BALDE' },
    { value: 'BANDEJ', label: 'BANDEJA' },
    { value: 'BARRA', label: 'BARRA' },
    { value: 'BISNAG', label: 'BISNAGA' },
    { value: 'BLOCO', label: 'BLOCO' },
    { value: 'BOBINA', label: 'BOBINA' },
    { value: 'BOMBON', label: 'BOMBONA' },
    { value: 'CAPS', label: 'CAPSULA' },
    { value: 'CARTEL', label: 'CARTELA' },
    { value: 'CENTO', label: 'CENTO' },
    { value: 'CJ', label: 'CONJUNTO (CJ)' },
    { value: 'CM', label: 'CENTIMETRO (CM)' },
    { value: 'CM2', label: 'CENTIMETRO QUADRADO (CM2)' },
    { value: 'CX', label: 'CAIXA (CX)' },
    { value: 'CX2', label: 'CAIXA COM 2 UNIDADES' },
    { value: 'CX3', label: 'CAIXA COM 3 UNIDADES' },
    { value: 'CX5', label: 'CAIXA COM 5 UNIDADES' },
    { value: 'CX10', label: 'CAIXA COM 10 UNIDADES' },
    { value: 'CX15', label: 'CAIXA COM 15 UNIDADES' },
    { value: 'CX20', label: 'CAIXA COM 20 UNIDADES' },
    { value: 'CX25', label: 'CAIXA COM 25 UNIDADES' },
    { value: 'CX50', label: 'CAIXA COM 50 UNIDADES' },
    { value: 'CX100', label: 'CAIXA COM 100 UNIDADES' },
    { value: 'DISP', label: 'DISPLAY' },
    { value: 'DZ', label: 'DUZIA' },
    { value: 'EMBAL', label: 'EMBALAGEM' },
    { value: 'FARDO', label: 'FARDO' },
    { value: 'FL', label: 'FOLHA' },
    { value: 'FR', label: 'FRASCO' },
    { value: 'GL', label: 'GALÃO' },
    { value: 'GF', label: 'GARRAFA (GF)' },
    { value: 'G', label: 'GRAMAS' },
    { value: 'JG', label: 'JOGO' },
    { value: 'KG', label: 'QUILOGRAMA (KG)' },
    { value: 'KIT', label: 'KIT' },
    { value: 'LATA', label: 'LATA' },
    { value: 'L', label: 'LITRO' },
    { value: 'M', label: 'METRO (M)' },
    { value: 'M2', label: 'METRO QUADRADO (M2)' },
    { value: 'M3', label: 'METRO CÚBICO (M3)' },
    { value: 'MILHEI', label: 'MILHEIRO' },
    { value: 'ML', label: 'MILILITRO (ML)' },
    { value: 'MWH', label: 'MEGAWATT HORA (MWH)' },
    { value: 'PACOTE', label: 'PACOTE' },
    { value: 'PALETE', label: 'PALETE' },
    { value: 'PR', label: 'PARES' },
    { value: 'PC', label: 'PEÇA (PC)' },
    { value: 'POTE', label: 'POTE' },
    { value: 'K', label: 'QUILATE (K)' },
    { value: 'RESMA', label: 'RESMA' },
    { value: 'ROLO', label: 'ROLO' },
    { value: 'SACO', label: 'SACO' },
    { value: 'SACOLA', label: 'SACOLA' },
    { value: 'TAMBOR', label: 'TAMBOR' },
    { value: 'TANQUE', label: 'TANQUE' },
    { value: 'TON', label: 'TONELADA (TON)' },
    { value: 'TUBO', label: 'TUBO' },
    { value: 'UN', label: 'UNIDADE (UN)' },
    { value: 'VASIL', label: 'VASILHAME' },
    { value: 'VIDRO', label: 'VIDRO' },
];
